### ISSUE TITLE
Launch seeded database

### ISSUE THREAD

**Issue by citylights521** [aprilleperez/studybuddy#27]

**Comment by maalbaneze** [comment]
Spoke with Joe.  Assuming we use Sequelize, once we build the sequelize functions to build the database structure for our project (it builds the schema), we populate it with the seeds.sql file I have built for all the users.   Initializing sequelize should build a "seeders" folder for the seeds file.

**Comment by maalbaneze** [comment]
Have it working on my branch but not on Aprille's routes branch

**Comment by maalbaneze** [comment]
Using a set timeout of 3000 (3 seconds) to force the Users data to be seeded before the Survey data.  Unclear why this happens problematically on route branch but not database branch.
