### ISSUE TITLE
start structuring DB

### ISSUE THREAD

**Issue by citylights521** [aprilleperez/studybuddy#8]

**Comment by maalbaneze** [comment]
One important note as we used BOOLEAN values for the meetvirtual and meetIP fields in the usersearch table:  both cannot be false or there will be no form of study session requested.  If meetIP is false, meetvirtual must be true.  Need to ensure that in our code on the user survey.

**Comment by maalbaneze** [comment]
Concern that there is a db difference between MySql and Sequelize as Sequelize creates its own standard field names (i.e., user vs username).
