### ISSUE TITLE
Issue:  Matches and Favorites for additional surveys are not distinguished from each other 

### ISSUE THREAD

**Issue by maalbaneze** [aprilleperez/studybuddy#88]
When an additional survey is generated, new matches and new selected favorites are indistinguishable.  In other words, the user doesn't know which matches on the matches page are for which sub-topic, and the same on the favorites page.  The card for the matches and favorites doesn't display sub-topic.

**Comment by citylights521** [comment]
Unfortunately we've accepted our fate on this one considering the time. For future development!
